var searchData=
[
  ['t_0',['t',['../struct_ray_hit_ab7d376ee6622c514e0002d86a7aabe82.html#ab7d376ee6622c514e0002d86a7aabe82',1,'RayHit']]],
  ['technical_5fterms_2emd_1',['technical_terms.md',['../technical__terms_8md.html',1,'']]],
  ['tex_5fcoords_2',['tex_coords',['../struct_internal_vertices_a8a64cdb2164ccef11d4d89160471f720.html#a8a64cdb2164ccef11d4d89160471f720',1,'InternalVertices::tex_coords'],['../struct_tri_mesh_a302cf14c693b3caff0f315af90933f71.html#a302cf14c693b3caff0f315af90933f71',1,'TriMesh::tex_coords']]],
  ['texture_3',['texture',['../struct_material_a2c6d6ff284d128bc307fbef90c10b8c0.html#a2c6d6ff284d128bc307fbef90c10b8c0',1,'Material']]],
  ['texture_5fname_4',['texture_name',['../struct_internal_material_aba2faaf548c72d0a9f9ad8a6124cd5fd.html#aba2faaf548c72d0a9f9ad8a6124cd5fd',1,'InternalMaterial']]],
  ['third_20level_20heading_5',['Third Level Heading',['../md_sources_2_x_e7_x_a7_x_b_b_x_e6_x_a4_x8_d_x_e3_x83_x_a1_x_e3_x83_x_a2.html#autotoc_md2',1,'Third Level Heading'],['../md_sources_2to_qtmemo.html#autotoc_md54',1,'Third Level Heading'],['../md_sources_2updatesandmemo.html#autotoc_md59',1,'Third Level Heading'],['../md__doxygen_2memo.html#autotoc_md198',1,'Third Level Heading'],['../md__doxygen_2updates.html#autotoc_md374',1,'Third Level Heading']]],
  ['toeigen_6',['toEigen',['../conversion__utils_8h_a0c89f83afd541b851753ffb491ff309d.html#a0c89f83afd541b851753ffb491ff309d',1,'conversion_utils.h']]],
  ['toqt_7',['toQt',['../conversion__utils_8h_acceab72295bcf0fed52969a98c77883e.html#acceab72295bcf0fed52969a98c77883e',1,'conversion_utils.h']]],
  ['toqtmemo_8',['toQtmemo',['../md_sources_2to_qtmemo.html',1,'']]],
  ['toqtmemo_2emd_9',['toQtmemo.md',['../to_qtmemo_8md.html',1,'']]],
  ['triangles_10',['triangles',['../struct_internal_triangles_ac8058fe07f9b104bcc9e8e1c4bf6f9aa.html#ac8058fe07f9b104bcc9e8e1c4bf6f9aa',1,'InternalTriangles::triangles'],['../struct_tri_mesh_a11c338168f69aa70225c87fc7c42f98e.html#a11c338168f69aa70225c87fc7c42f98e',1,'TriMesh::triangles']]],
  ['trimesh_11',['TriMesh',['../struct_tri_mesh.html',1,'']]],
  ['trimesh_2ecpp_12',['TriMesh.cpp',['../_tri_mesh_8cpp.html',1,'']]],
  ['trimesh_2eh_13',['TriMesh.h',['../_tri_mesh_8h.html',1,'']]],
  ['tt_14',['tt',['../md__doxygen_2memo__film__interaction.html#autotoc_md221',1,'&lt;tt&gt;Camera::screenView(int i, int j)&lt;/tt&gt;'],['../md_sources_2to_qtmemo.html#autotoc_md47',1,'&lt;tt&gt;display()&lt;/tt&gt; → &lt;tt&gt;paintGL()&lt;/tt&gt;'],['../md__doxygen_2memo__film__interaction.html#autotoc_md215',1,'&lt;tt&gt;FilmBuffer::addSample(int i, int j, const Eigen::Vector3d\&amp; color)&lt;/tt&gt;'],['../md__doxygen_2memo__film__interaction.html#autotoc_md219',1,'&lt;tt&gt;FilmBuffer::getFilmBufferPtr() const&lt;/tt&gt;'],['../md__doxygen_2memo__film__interaction.html#autotoc_md213',1,'&lt;tt&gt;FilmBuffer::init(int width, int height)&lt;/tt&gt;'],['../md__doxygen_2memo__film__interaction.html#autotoc_md217',1,'&lt;tt&gt;FilmBuffer::updateFilmBuffer()&lt;/tt&gt;'],['../md__doxygen_2memo__film__interaction.html#autotoc_md211',1,'&lt;tt&gt;MyOpenGLWidget_camera::debug_computeNormalColor(const Ray\&amp; ray)&lt;/tt&gt;'],['../md__doxygen_2memo__wip__raytracing.html#autotoc_md276',1,'&lt;tt&gt;MyOpenGLWidget_camera::debug_computeNormalColor(const Ray\&amp; ray)&lt;/tt&gt;'],['../md__doxygen_2memo__film__interaction.html#autotoc_md223',1,'&lt;tt&gt;MyOpenGLWidget_camera::m_film&lt;/tt&gt;'],['../md__doxygen_2memo__film__interaction.html#autotoc_md209',1,'&lt;tt&gt;MyOpenGLWidget_camera::updateRayTracing()&lt;/tt&gt;'],['../md__doxygen_2memo__wip__raytracing.html#autotoc_md274',1,'&lt;tt&gt;MyOpenGLWidget_camera::updateRayTracing()&lt;/tt&gt;'],['../md_sources_2to_qtmemo.html#autotoc_md49',1,'&lt;tt&gt;resize()&lt;/tt&gt; → &lt;tt&gt;resizeGL()&lt;/tt&gt;']]],
  ['tt_20→_20tt_20paintgl_20tt_15',['&lt;tt&gt;display()&lt;/tt&gt; → &lt;tt&gt;paintGL()&lt;/tt&gt;',['../md_sources_2to_qtmemo.html#autotoc_md47',1,'']]],
  ['tt_20→_20tt_20qtimer_20tt_20カスタムスロット_16',['&lt;tt&gt;idle()&lt;/tt&gt; → &lt;tt&gt;QTimer&lt;/tt&gt; + カスタムスロット',['../md_sources_2to_qtmemo.html#autotoc_md51',1,'']]],
  ['tt_20→_20tt_20resizegl_20tt_17',['&lt;tt&gt;resize()&lt;/tt&gt; → &lt;tt&gt;resizeGL()&lt;/tt&gt;',['../md_sources_2to_qtmemo.html#autotoc_md49',1,'']]],
  ['tt_20が一定間隔で時間切れ（timeout）になるたびに_18',['connect関数；&lt;tt&gt;QTimer&lt;/tt&gt; が一定間隔で時間切れ（timeout）になるたびに',['../md__doxygen_2memo__wip__raytracing.html#autotoc_md267',1,'']]],
  ['tt_20では投影→ビューポート→視野_20の順なのか？_19',['✅ ではなぜ &lt;tt&gt;paintGL()&lt;/tt&gt; では投影→ビューポート→視野 の順なのか？',['../md__doxygen_2coordinate__transformation1.html#autotoc_md161',1,'']]],
  ['tt_20とは？_20',['tt とは？',['../additional_inf_1.html#autotoc_md74',1,'1. &lt;tt&gt;std::vector\&lt;Eigen::Vector3d\&gt;&lt;/tt&gt; とは？'],['../additional_inf_1.html#autotoc_md76',1,'2. &lt;tt&gt;Eigen::Vector3d&lt;/tt&gt; とは？']]],
  ['tt_20に色を蓄積_21',['7. &lt;tt&gt;FilmBuffer&lt;/tt&gt; に色を蓄積',['../md__doxygen_2function__myopenglwigetcamera.html#autotoc_md189',1,'']]],
  ['tt_20の呼び出しをスケジュール_22',['12. &lt;tt&gt;paintGL()&lt;/tt&gt; の呼び出しをスケジュール',['../md__doxygen_2function__myopenglwigetcamera.html#autotoc_md194',1,'']]],
  ['tt_20の流れと操作対象_20strong_23',['&lt;strong&gt;&lt;tt&gt;glMatrixMode&lt;/tt&gt; の流れと操作対象&lt;/strong&gt;',['../md__doxygen_2_open_g_l__func.html#autotoc_md322',1,'']]],
  ['tt_20は何？_24',['3. &lt;tt&gt;Eigen::aligned_allocator\&lt;Eigen::Vector3d\&gt;&lt;/tt&gt; は何？',['../additional_inf_1.html#autotoc_md78',1,'']]],
  ['tt_20カスタムスロット_25',['&lt;tt&gt;idle()&lt;/tt&gt; → &lt;tt&gt;QTimer&lt;/tt&gt; + カスタムスロット',['../md_sources_2to_qtmemo.html#autotoc_md51',1,'']]],
  ['tt_20関数の概要_20strong_26',['&lt;strong&gt;&lt;tt&gt;glMatrixMode&lt;/tt&gt; 関数の概要&lt;/strong&gt;',['../md__doxygen_2_open_g_l__func.html#autotoc_md311',1,'']]],
  ['tt_20関数を自動的に呼び出す_27',['&lt;tt&gt;MyOpenGLWidget_camera::updateRayTracing()&lt;/tt&gt; 関数を自動的に呼び出す',['../md__doxygen_2memo__wip__raytracing.html#autotoc_md268',1,'']]],
  ['tt_20）：_28',['OpenGLの描画順序（実際の&lt;tt&gt;paintGL()&lt;/tt&gt;）：',['../md__doxygen_2coordinate__transformation1.html#autotoc_md162',1,'']]],
  ['tt_20）_29',['tt ）',['../md__doxygen_2open_g_l__basis.html#autotoc_md291',1,'🔵 2. 初期化（&lt;tt&gt;initializeGL()&lt;/tt&gt; / &lt;tt&gt;init()&lt;/tt&gt;）'],['../md__doxygen_2open_g_l__basis.html#autotoc_md293',1,'🔵 3. 描画（&lt;tt&gt;paintGL()&lt;/tt&gt; / &lt;tt&gt;display()&lt;/tt&gt;）'],['../md__doxygen_2open_g_l__basis.html#autotoc_md295',1,'🔵 4. 再描画要求（&lt;tt&gt;update()&lt;/tt&gt; or &lt;tt&gt;glutPostRedisplay()&lt;/tt&gt;）']]],
  ['tt_20b_20tt_20strong_20_3a_20青（blue）成分_30',['- &lt;strong&gt;&lt;tt&gt;B&lt;/tt&gt;&lt;/strong&gt;: 青（Blue）成分',['../additional_info_buffer.html#autotoc_md114',1,'']]],
  ['tt_20camera_3a_3ascreenview_20int_20i_20int_20j_20tt_31',['&lt;tt&gt;Camera::screenView(int i, int j)&lt;/tt&gt;',['../md__doxygen_2memo__film__interaction.html#autotoc_md221',1,'']]],
  ['tt_20display_20tt_20→_20tt_20paintgl_20tt_32',['&lt;tt&gt;display()&lt;/tt&gt; → &lt;tt&gt;paintGL()&lt;/tt&gt;',['../md_sources_2to_qtmemo.html#autotoc_md47',1,'']]],
  ['tt_20display_20tt_20）_33',['🔵 3. 描画（&lt;tt&gt;paintGL()&lt;/tt&gt; / &lt;tt&gt;display()&lt;/tt&gt;）',['../md__doxygen_2open_g_l__basis.html#autotoc_md293',1,'']]],
  ['tt_20eigen_3a_3aaligned_5fallocator_20eigen_3a_3avector3d_20tt_20は何？_34',['3. &lt;tt&gt;Eigen::aligned_allocator\&lt;Eigen::Vector3d\&gt;&lt;/tt&gt; は何？',['../additional_inf_1.html#autotoc_md78',1,'']]],
  ['tt_20eigen_3a_3avector3d_20tt_20とは？_35',['2. &lt;tt&gt;Eigen::Vector3d&lt;/tt&gt; とは？',['../additional_inf_1.html#autotoc_md76',1,'']]],
  ['tt_20filmbuffer_20tt_20に色を蓄積_36',['7. &lt;tt&gt;FilmBuffer&lt;/tt&gt; に色を蓄積',['../md__doxygen_2function__myopenglwigetcamera.html#autotoc_md189',1,'']]],
  ['tt_20filmbuffer_3a_3aaddsample_20int_20i_20int_20j_20const_20eigen_3a_3avector3d_20color_20tt_37',['&lt;tt&gt;FilmBuffer::addSample(int i, int j, const Eigen::Vector3d\&amp; color)&lt;/tt&gt;',['../md__doxygen_2memo__film__interaction.html#autotoc_md215',1,'']]],
  ['tt_20filmbuffer_3a_3agetfilmbufferptr_20const_20tt_38',['&lt;tt&gt;FilmBuffer::getFilmBufferPtr() const&lt;/tt&gt;',['../md__doxygen_2memo__film__interaction.html#autotoc_md219',1,'']]],
  ['tt_20filmbuffer_3a_3ainit_20int_20width_20int_20height_20tt_39',['&lt;tt&gt;FilmBuffer::init(int width, int height)&lt;/tt&gt;',['../md__doxygen_2memo__film__interaction.html#autotoc_md213',1,'']]],
  ['tt_20filmbuffer_3a_3aupdatefilmbuffer_20tt_40',['&lt;tt&gt;FilmBuffer::updateFilmBuffer()&lt;/tt&gt;',['../md__doxygen_2memo__film__interaction.html#autotoc_md217',1,'']]],
  ['tt_20glmatrixmode_20tt_20の流れと操作対象_20strong_41',['&lt;strong&gt;&lt;tt&gt;glMatrixMode&lt;/tt&gt; の流れと操作対象&lt;/strong&gt;',['../md__doxygen_2_open_g_l__func.html#autotoc_md322',1,'']]],
  ['tt_20glmatrixmode_20tt_20関数の概要_20strong_42',['&lt;strong&gt;&lt;tt&gt;glMatrixMode&lt;/tt&gt; 関数の概要&lt;/strong&gt;',['../md__doxygen_2_open_g_l__func.html#autotoc_md311',1,'']]],
  ['tt_20glutpostredisplay_20tt_20）_43',['🔵 4. 再描画要求（&lt;tt&gt;update()&lt;/tt&gt; or &lt;tt&gt;glutPostRedisplay()&lt;/tt&gt;）',['../md__doxygen_2open_g_l__basis.html#autotoc_md295',1,'']]],
  ['tt_20idle_20tt_20→_20tt_20qtimer_20tt_20カスタムスロット_44',['&lt;tt&gt;idle()&lt;/tt&gt; → &lt;tt&gt;QTimer&lt;/tt&gt; + カスタムスロット',['../md_sources_2to_qtmemo.html#autotoc_md51',1,'']]],
  ['tt_20init_20tt_20）_45',['🔵 2. 初期化（&lt;tt&gt;initializeGL()&lt;/tt&gt; / &lt;tt&gt;init()&lt;/tt&gt;）',['../md__doxygen_2open_g_l__basis.html#autotoc_md291',1,'']]],
  ['tt_20initializegl_20tt_20tt_20init_20tt_20）_46',['🔵 2. 初期化（&lt;tt&gt;initializeGL()&lt;/tt&gt; / &lt;tt&gt;init()&lt;/tt&gt;）',['../md__doxygen_2open_g_l__basis.html#autotoc_md291',1,'']]],
  ['tt_20myopenglwidget_5fcamera_3a_3adebug_5fcomputenormalcolor_20const_20ray_20ray_20tt_47',['tt MyOpenGLWidget_camera::debug_computeNormalColor const Ray ray tt',['../md__doxygen_2memo__film__interaction.html#autotoc_md211',1,'&lt;tt&gt;MyOpenGLWidget_camera::debug_computeNormalColor(const Ray\&amp; ray)&lt;/tt&gt;'],['../md__doxygen_2memo__wip__raytracing.html#autotoc_md276',1,'&lt;tt&gt;MyOpenGLWidget_camera::debug_computeNormalColor(const Ray\&amp; ray)&lt;/tt&gt;']]],
  ['tt_20myopenglwidget_5fcamera_3a_3am_5ffilm_20tt_48',['&lt;tt&gt;MyOpenGLWidget_camera::m_film&lt;/tt&gt;',['../md__doxygen_2memo__film__interaction.html#autotoc_md223',1,'']]],
  ['tt_20myopenglwidget_5fcamera_3a_3aupdateraytracing_20tt_49',['tt MyOpenGLWidget_camera::updateRayTracing tt',['../md__doxygen_2memo__film__interaction.html#autotoc_md209',1,'&lt;tt&gt;MyOpenGLWidget_camera::updateRayTracing()&lt;/tt&gt;'],['../md__doxygen_2memo__wip__raytracing.html#autotoc_md274',1,'&lt;tt&gt;MyOpenGLWidget_camera::updateRayTracing()&lt;/tt&gt;']]],
  ['tt_20myopenglwidget_5fcamera_3a_3aupdateraytracing_20tt_20関数を自動的に呼び出す_50',['&lt;tt&gt;MyOpenGLWidget_camera::updateRayTracing()&lt;/tt&gt; 関数を自動的に呼び出す',['../md__doxygen_2memo__wip__raytracing.html#autotoc_md268',1,'']]],
  ['tt_20or_20tt_20glutpostredisplay_20tt_20）_51',['🔵 4. 再描画要求（&lt;tt&gt;update()&lt;/tt&gt; or &lt;tt&gt;glutPostRedisplay()&lt;/tt&gt;）',['../md__doxygen_2open_g_l__basis.html#autotoc_md295',1,'']]],
  ['tt_20paintgl_20tt_52',['&lt;tt&gt;display()&lt;/tt&gt; → &lt;tt&gt;paintGL()&lt;/tt&gt;',['../md_sources_2to_qtmemo.html#autotoc_md47',1,'']]],
  ['tt_20paintgl_20tt_20では投影→ビューポート→視野_20の順なのか？_53',['✅ ではなぜ &lt;tt&gt;paintGL()&lt;/tt&gt; では投影→ビューポート→視野 の順なのか？',['../md__doxygen_2coordinate__transformation1.html#autotoc_md161',1,'']]],
  ['tt_20paintgl_20tt_20の呼び出しをスケジュール_54',['12. &lt;tt&gt;paintGL()&lt;/tt&gt; の呼び出しをスケジュール',['../md__doxygen_2function__myopenglwigetcamera.html#autotoc_md194',1,'']]],
  ['tt_20paintgl_20tt_20）：_55',['OpenGLの描画順序（実際の&lt;tt&gt;paintGL()&lt;/tt&gt;）：',['../md__doxygen_2coordinate__transformation1.html#autotoc_md162',1,'']]],
  ['tt_20paintgl_20tt_20tt_20display_20tt_20）_56',['🔵 3. 描画（&lt;tt&gt;paintGL()&lt;/tt&gt; / &lt;tt&gt;display()&lt;/tt&gt;）',['../md__doxygen_2open_g_l__basis.html#autotoc_md293',1,'']]],
  ['tt_20qtimer_20tt_20が一定間隔で時間切れ（timeout）になるたびに_57',['connect関数；&lt;tt&gt;QTimer&lt;/tt&gt; が一定間隔で時間切れ（timeout）になるたびに',['../md__doxygen_2memo__wip__raytracing.html#autotoc_md267',1,'']]],
  ['tt_20qtimer_20tt_20カスタムスロット_58',['&lt;tt&gt;idle()&lt;/tt&gt; → &lt;tt&gt;QTimer&lt;/tt&gt; + カスタムスロット',['../md_sources_2to_qtmemo.html#autotoc_md51',1,'']]],
  ['tt_20resize_20tt_20→_20tt_20resizegl_20tt_59',['&lt;tt&gt;resize()&lt;/tt&gt; → &lt;tt&gt;resizeGL()&lt;/tt&gt;',['../md_sources_2to_qtmemo.html#autotoc_md49',1,'']]],
  ['tt_20resizegl_20tt_60',['&lt;tt&gt;resize()&lt;/tt&gt; → &lt;tt&gt;resizeGL()&lt;/tt&gt;',['../md_sources_2to_qtmemo.html#autotoc_md49',1,'']]],
  ['tt_20std_3a_3avector_20eigen_3a_3avector3d_20tt_20とは？_61',['1. &lt;tt&gt;std::vector\&lt;Eigen::Vector3d\&gt;&lt;/tt&gt; とは？',['../additional_inf_1.html#autotoc_md74',1,'']]],
  ['tt_20strong_20_3a_20青（blue）成分_62',['- &lt;strong&gt;&lt;tt&gt;B&lt;/tt&gt;&lt;/strong&gt;: 青（Blue）成分',['../additional_info_buffer.html#autotoc_md114',1,'']]],
  ['tt_20tt_20display_20tt_20）_63',['🔵 3. 描画（&lt;tt&gt;paintGL()&lt;/tt&gt; / &lt;tt&gt;display()&lt;/tt&gt;）',['../md__doxygen_2open_g_l__basis.html#autotoc_md293',1,'']]],
  ['tt_20tt_20init_20tt_20）_64',['🔵 2. 初期化（&lt;tt&gt;initializeGL()&lt;/tt&gt; / &lt;tt&gt;init()&lt;/tt&gt;）',['../md__doxygen_2open_g_l__basis.html#autotoc_md291',1,'']]],
  ['tt_20update_20tt_20or_20tt_20glutpostredisplay_20tt_20）_65',['🔵 4. 再描画要求（&lt;tt&gt;update()&lt;/tt&gt; or &lt;tt&gt;glutPostRedisplay()&lt;/tt&gt;）',['../md__doxygen_2open_g_l__basis.html#autotoc_md295',1,'']]]
];
