@startuml inline_umlgraph_2.png
User -> MainWindow : on_fovSlider_valueChanged(int value)\n FOV sliderをいじる
MainWindow -> MyOpenGLWidget : setCameraFov(float fov)\n カメラFOVを更新
MyOpenGLWidget -> Camera : setFov(float cameraFov)\n 新しい FOVを設置
Camera --> MyOpenGLWidget : getFov(float cameraFov)\n FOVを更新
@enduml
